### ISSUE TITLE
[JSON Schema] Express Time resource as custom type 'time'

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/lwm2m-types-js#23]
Time Unix Time. A signed integer
representing the number of seconds since
Jan 1st, 1970 in the UTC time zone.
Represented as an ASCII
integer.

For example, 1476186613
seconds since Jan 01 1970,
which represents Tuesday,
11-Oct-16 11:50:13 UTC,
are represented as the
ASCII string
"1476186613", which has
10 characters/bytes.

Same representation as Integer.

Page 96 http://www.openmobilealliance.org/release/lightweightm2m/V1_0-20170208-A/OMA-TS-LightweightM2M-V1_0-20170208-A.pdf

## Example

add `type`: `time`, user-defined keywords are supported in AJV: https://ajv.js.org/keywords.html

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "$id": "https://github.com/NordicSemiconductor/lwm2m-types-js/blob/saga/LwM2MDocument.schema.json",
  "title": "LwM2M JSON Schema",
  "description": "JSON schema for expressing LwM2M resources as JSON",
  "properties": {
    "6": {
      "properties": {
        "5": {
          "type": "time",
          "minimum": 1000000000,
          "title": "Timestamp",
          "description": "The timestamp of when the location measurement was performed. Unix Time. A signed integer representing the number of seconds since Jan 1 st, 1970 in the UTC time zone."
        },
      },
    },
  },
}
```

**Comment by MLopezJ** [comment]
# How to represent date in Json Schema?

Using the keyword `type` as `string` and the `format` keyword as `date-time`

``` json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "$id": "https://github.com/NordicSemiconductor/lwm2m-types-js/blob/saga/LwM2MDocument.schema.json",
  "title": "LwM2M JSON Schema",
  "description": "JSON schema for expressing LwM2M resources as JSON",
  "properties": {
    "6": {
      "properties": {
        "5": {
          "type": "string",
          "format": "date-time",
          "title": "Timestamp",
        },
      },
    },
  },
}
```

[More info](https://json-schema.org/understanding-json-schema/reference/string.html#:~:text=%22date%2Dtime%22%3A%20Date%20and%20time%20together%2C%20for%20example%2C%202018%2D11%2D13T20%3A20%3A39%2B00%3A00)

# What is the expected value according to LwM2M XML definition?

2 examples:

[Object 6](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/6.xml)
``` xml
<Item ID="5">
  <Name>Timestamp</Name>
  <Operations>R</Operations>
  <MultipleInstances>Single</MultipleInstances>
  <Mandatory>Mandatory</Mandatory>
  <Type>Time</Type>
  <RangeEnumeration></RangeEnumeration>
  <Units></Units>
  <Description><![CDATA[The timestamp of when the location measurement was performed.]]></Description>
</Item>
```

[Object 3303](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/3303.xml)
``` xml

<Item ID="5518">
  <Name>Timestamp</Name>
  <Operations>R</Operations>
  <MultipleInstances>Single</MultipleInstances>
  <Mandatory>Optional</Mandatory>
  <Type>Time</Type>
  <RangeEnumeration></RangeEnumeration>
  <Units></Units>
  <Description>The timestamp of when the measurement was performed.</Description>
</Item>
```

# What is the LwM2M definition of Time type ?

`Unix Time. A signed integer representing the number of seconds since Jan 1st, 1970 in the UTC time zone.` 

[LwM2M documentation pag 96](https://www.openmobilealliance.org/release/lightweightm2m/V1_0-20170208-A/OMA-TS-LightweightM2M-V1_0-20170208-A.pdf)

# How does the provided value look like in the shadow?

Object 3303 prop 5518: Temperature 
``` json
{
  "Timestamp": "2022-10-07T13:33:22Z"
}
```

Object 6, prop 5: Location
``` json
{
  "Timestamp": "1970-01-01T00:00:00Z",
}
```

# Problem
The expected format according to the standard is `UNIX TIME` but provided value in shadow follows `ISO 8601 date-time`

**Comment by MLopezJ** [comment]
# How to represent UNIX TIME in Json Schema ?

``` json

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "$id": "https://github.com/NordicSemiconductor/lwm2m-types-js/blob/saga/LwM2MDocument.schema.json",
  "title": "LwM2M JSON Schema",
  "description": "JSON schema for expressing LwM2M resources as JSON",
  "properties": {
    "6": {
      "properties": {
        "5": {
          "type": "integer",
          "minimum": -864e12,
          "maximum": 864e12,
          "title": "Timestamp",
        },
      },
    },
  },
}
```
[stackoverflow](https://stackoverflow.com/a/63749404)

Because UNIX TIME definition says: `it is the number of seconds between a particular date and the Unix Epoch` [unixtimestamp](https://www.unixtimestamp.com/)


Other alternative could be add `format` keyword as `date-time` in object definition 

``` json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "$id": "https://github.com/NordicSemiconductor/lwm2m-types-js/blob/saga/LwM2MDocument.schema.json",
  "title": "LwM2M JSON Schema",
  "description": "JSON schema for expressing LwM2M resources as JSON",
  "properties": {
    "6": {
      "properties": {
        "5": {
          "type": "integer",
          "minimum": -864e12,
          "maximum": 864e12,
          "title": "Timestamp",
          "format": "date-time",
        },
      },
    },
  },
}
```

However, this is not a real solution because "format": "date-time" only work on string type and LwM2M described value as integer: 
- [Json Schema documentation](https://json-schema.org/understanding-json-schema/reference/string.html#:~:text=%22date%2Dtime%22%3A%20Date%20and%20time%20together%2C%20for%20example%2C%202018%2D11%2D13T20%3A20%3A39%2B00%3A00) 
- [pag 96](https://www.openmobilealliance.org/release/lightweightm2m/V1_0-20170208-A/OMA-TS-LightweightM2M-V1_0-20170208-A.pdf)

[here](https://stackoverflow.com/a/53559752) is described another alternative using `ajv`, however that does not work neither because the expected value is `UNIX TIME` format and not `ISO 8601` format.

**Comment by coderbyheart** [comment]
@MLopezJ 
> How does the provided value look like in the shadow?

This is not relevant for this project.
